name = "leonw-ong"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"

# Assets configuration for static site
[assets]
directory = "./dist"

# Optional: Configure custom domain
# routes = [
#   { pattern = "leonw.ong", custom_domain = true }
# ]

# Environment variables (if needed)
[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging" 