name = "leonw-ong"
compatibility_date = "2025-08-15"

# Build configuration
[build]
command = "npm run build"

# Static assets configuration for Workers
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Enable preview URLs
preview_urls = true

# Optional: Configure custom domain
# routes = [
#   { pattern = "leonw.ong", custom_domain = true }
# ]

# Environment variables (if needed)
[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging" 